server {
    listen 80;
    server_name localhost;

    # Root directory serving compiled static assets
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Redirect all resource lookups back to index.html for React Router routing
        try_files $uri $uri/ /index.html;
    }

    # Centralize 50x server errors
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
